import type { Metadata } from "next";
import { Geist, Geist_Mono, Bebas_Neue } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ResizeHandler from "./components/ResizeHandler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Caffinity",
  description: "Generated by create next app",
  icons: {
    icon: "/icon3.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ scrollBehavior: 'auto' }}>
      <head>
        <link rel="icon" href="/icon3.ico" sizes="any" />
        <link rel="icon" type="image/png" href="/icon.png" />
        <link rel="shortcut icon" href="/icon3.ico" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${bebasNeue.variable}`}>
        <ResizeHandler />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
